---
title: "test0112"
author: "Ivan Chen"
date: "2019年1月12日"
output: html_document
---

```{r}
library(tidyverse)
alldf <- readRDS("./alldf.rds")
# alldf

dfbeforefilter <- readRDS("./all.rds")

mvnStat <- dfbeforefilter %>% 
  filter(!is.na(pmoney) & !is.na(money)) %>% 
  group_by(nation) %>% 
  summarise(mpm = mean(pmoney), mm = mean(money), sdpm= sd(pmoney), sdm=sd(money))

mvnStat <- mvnStat %>% 
  mutate(mLowBound=mm-3*sdm, mUpBound=mm+3*sdm) %>% 
  mutate(pLowBound=mpm-3*sdpm, pUpBound=mpm+3*sdpm)

mvnStat

# Samples amount: by nations
dfbeforefilter %>% 
  group_by(nation) %>% 
  count

# Single filter out outliers
dfbeforefilter %>% 
  filter(!is.na(pmoney) & !is.na(money)) %>% 
  filter(nation==1) %>% 
  # filter(money<mvnStat$mLowBound[1])
  filter(money<mvnStat$mUpBound[1])
  # nrow # 3000


dfAfterFilter <- data.frame()
t_vec <- c()

# Multiple filter out outliers
for (i in 1:nrow(mvnStat)){
  
  # print(mvnStat[i,]$nation)
  
  tempdf <- dfbeforefilter %>%
    filter(!is.na(pmoney) & !is.na(money)) %>%
    filter(nation == mvnStat[i, ]$nation) %>%
    # filter(money<mvnStat$mLowBound[1])
    filter(money<mvnStat$mUpBound[i], pmoney<mvnStat$pUpBound[i])

  tempdf %>% 
    nrow() %>% print()
  
  t_vec <- c(t_vec, nrow(tempdf))
  # dfbeforefilter %>%
  #   filter(!is.na(pmoney) & !is.na(money)) %>%
  #   filter(nation == mvnStat[i, ]$nation) %>%
  #   # filter(money<mvnStat$mLowBound[1])
  #   filter(pmoney>mvnStat$pUpBound[i]) %>% 
  #   nrow() %>% print()
  
  dfAfterFilter <- rbind(dfAfterFilter, tempdf)
  
}

saveRDS(dfAfterFilter, "dfAfterFilter.rds")
 
```

```{r}
BVAcount <- dfbeforefilter %>% 
  filter(!is.na(pmoney) & !is.na(money)) %>%
  group_by(nation) %>% 
  count

BVAcount <- cbind(BVAcount, n_filtered=t_vec)
BVAcount
```



```{r}
mvnStat$mUpBound[1]
```


```{r}
alldf %>% 
  mutate(nation=as.factor(nation),type=as.factor(type)) %>% 
  ggplot(aes(x=nation, fill=type)) + 
  geom_bar(position="fill") +
  coord_flip() + 
  # facet_wrap(~re) +
  ggtitle("各國跟團百分比(%)") +
  ylab("跟團性質") + xlab("國家") +
  scale_y_continuous(trans = "reverse")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

alldf %>% 
  mutate(nation=as.factor(nation),type=as.factor(type)) %>% 
  ggplot(aes(x=nation, fill=type)) + 
  geom_bar(position="fill") +
  # facet_wrap(~re) +
  ggtitle("各國跟團百分比(%)") +
  ylab("跟團性質") + xlab("國家") +
  scale_y_continuous(trans = "reverse")+
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

