---
title: "Travel Type"
output:
  html_document:
    highlight: textmate
    number_sections: yes
    theme: spacelab
    df_print: paged
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: true
  html_notebook:
    df_print: paged
    toc: yes
---
```{r}
alldf <- readRDS("./dfAfterFilter.rds")

library(ggplot2)
library(ggthemes)
library(extrafont)
library(scales)

colors <- c('#D0104C', '#DB4D6D', '#E83015',  '#F75C2F',
            '#E79460', '#E98B2A', '#9B6E23', '#F7C242',
            '#BEC23F', '#90B44B', '#66BAB7', '#1E88A8')

fill <- c(   '#E98B2A', '#9B6E23', '#F7C242',
            '#BEC23F', '#90B44B', '#66BAB7', '#1E88A8' )
par(family=('Heiti TC Light'))
```

```{r}
nation.df <- alldf %>% 
  group_by(year) %>% 
  count(year, nation) %>% 
  mutate(percent = n/sum(n)*100)

nation.df$nation <- factor(nation.df$nation, ordered = TRUE, levels = c(2, 1, 5, 6, 8, 4, 15))
levels(nation.df$nation) <- list("Others"= 15, "Singapore"= 4, "Western"= 8, "Asia"=6, "Korea"= 5, "Japan" = 1, "China" = 2)

nation.g <- nation.df %>%
  ggplot() + theme_classic() +  scale_fill_manual(values=fill) +
  geom_bar(aes(y =percent, x = year, fill = nation), stat="identity") +
  ylab("Percentage (%)") + xlab("Year") 

nation.g


```




```{r}
alldf <- readRDS("./all.rds")
alldf$type[(alldf$type == 3)] = 2  # 1: 跟團，2:自由行，3:混合
alldf$type[(alldf$type == 5)] = 4  
alldf %>% group_by(nation)  %>% count(nation, type) %>%  mutate(percent = n/sum(n))

# 畫直方圖
alldf <- alldf %>%
  mutate(moneyAll = money + pmoney) %>%
  mutate(moneyAve = moneyAll / stay) %>%
  mutate(money6Ave = money6 / stay) 

alldf %>% 
  group_by(nation) %>% 
  summarise_at(vars(btimes), mean, na.rm = TRUE)      

a <- alldf %>% filter (nation == 1) %>% select(moneyAll)
summary(a)

alldf %>% 
  group_by(nation) %>% 
  summarise_at(vars(moneyAve), mean, na.rm = TRUE)

alldf %>% 
  group_by(nation, type) %>% 
  summarise_at(vars(moneyAve), mean, na.rm = TRUE) %>% 
  arrange(desc(moneyAve))

alldf %>%
  group_by(nation) %>% 
  summarise_at(vars(stay), mean, na.rm = TRUE)
```

```{r plot}

# Type 4 bigger

alldf %>% 
  mutate(nation=as.factor(nation),type=as.factor(type)) %>% 
  ggplot(aes(x=nation, fill=type)) + 
  geom_bar(position="fill") +
  coord_flip() + 
  # facet_wrap(~re) +
  ggtitle("各國跟團百分比(%)") +
  ylab("跟團性質") + xlab("國家") +
  scale_y_continuous(trans = "reverse")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

alldf %>% 
  mutate(nation=as.factor(nation),type=as.factor(type)) %>% 
  ggplot(aes(x=nation, fill=type)) + 
  geom_bar(position="fill") +
  # facet_wrap(~re) +
  ggtitle("各國跟團百分比(%)") +
  ylab("跟團性質") + xlab("國家") +
  scale_y_continuous(trans = "reverse")+
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

# Type 1 bigger
alldf %>% 
  mutate(nation=as.factor(nation),type=as.factor(type)) %>% 
  arrange(type) %>% 
  ggplot(aes(x=nation, fill=type)) + 
  geom_bar(position="fill") +
  coord_flip() + 
  # facet_wrap(~re) +
  ggtitle("各國跟團百分比(%)") +
  ylab("跟團性質") + xlab("國家") +
  scale_y_continuous(trans = "reverse")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}



```

